# Jeffrey Lansford
# Makefile for Lab1
# January 18, 2019
all:
	# two commands for compiling the lex file and the produced C file to get
	# executable lab1
	lex wordlengthlab1.l
	gcc -o lab1 lex.yy.c
	
